language: cpp

dist: bionic

before_install:
  - sudo apt update
  - sudo apt install libopencv-dev

branches:
  only:
    - main

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --config release