language: cpp

jobs:
  include:
    - os: windows
      before_install:
        - choco install opencv
    - os: linux
      before_install:
        - sudo apt install libopencv-dev

branches:
  only:
    - main

script:
    - mkdir build
    - cd build
    - if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then
        cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..;
      else
        cmake ..;
      fi
    - cmake --build . --config release